//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDeDatos.ModeloDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_producto()
        {
            this.tb_fotos = new HashSet<tb_fotos>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string serieal { get; set; }
        public int id_marca { get; set; }
        public int id_tipo_producto { get; set; }
        public int id_persona { get; set; }
        public int id_espacio { get; set; }
    
        public virtual tb_espacio tb_espacio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_fotos> tb_fotos { get; set; }
        public virtual tb_marca tb_marca { get; set; }
        public virtual tb_persona tb_persona { get; set; }
        public virtual tb_tipo_producto tb_tipo_producto { get; set; }
    }
}
